<?php

declare(strict_types=1);
?>
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Mini ERP Laminas')->setSeparator(' - ')->setAutoEscape(false) ?>
    <link rel="icon" type="image/x-icon" href="/img/favicon.ico">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style>
        * {
            box-sizing: border-box;
        }

        body {
            margin: 0;
            font-family: Arial, Helvetica, sans-serif;
            background: #f5f7fb;
            color: #111827;
        }

        a {
            color: inherit;
        }
    </style>
</head>
<body>
    <?= $this->content ?>
</body>
</html>